name: servant-matrix-param
version: "0.1"

dependencies:
  - base < 5
  - servant == 0.5

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-matrix-param
  doctest:
    main: Doctest.hs
    source-dirs:
      - test
    dependencies:
      - doctest

library:
  source-dirs:
    - src
