resolver: lts-6.10
packages:
  - '.'
  - location:
      git: https://github.com/plow-technologies/servant-aeson-specs
      commit: "0.4"
    extra-dep: true
extra-deps:
  - servant-0.5
  - servant-server-0.5
flags:
  servant-matrix-param:
    with-servant-aeson-specs: true
    with-servant-server: true
