resolver: nightly-2016-10-04
packages:
  - '.'
extra-deps:
- hspec-golden-aeson-0.5.1.0
- servant-aeson-specs-0.6.0.0
- quickcheck-arbitrary-adt-0.3.1.0
- servant-0.9
- servant-server-0.9
- http-api-data-0.3.1
flags:
  servant-matrix-param:
    with-servant-aeson-specs: true
    with-servant-server: true
    with-servant-client: true
