resolver: lts-6.10
packages:
  - '.'
  - location:
      git: https://github.com/plow-technologies/servant-aeson-specs
      commit: c2a061d671d00f6f06dcf8b0f031ab51c7d4ac84
    extra-dep: true
extra-deps:
- hspec-golden-aeson-0.2.0.3
- quickcheck-arbitrary-adt-0.2.0.0
