resolver: nightly-2016-10-04
packages:
  - '.'
extra-deps:
- servant-aeson-specs-0.5.2.0
- servant-0.9
- servant-server-0.9
- http-api-data-0.3.1
flags:
  servant-matrix-param:
    with-servant-aeson-specs: true
    with-servant-server: true
    with-servant-client: true
