resolver: lts-19.6
packages:
  - '.'
extra-deps:
- servant-aeson-specs-0.6.1.0
flags:
  servant-matrix-param:
    with-servant-aeson-specs: true
    with-servant-server: true
    with-servant-client: true
allow-newer: true
